version: "3.8"

services:
  nginx:
    ports:
      - 8080:80
    volumes:
      - .:/laravel:consistent
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available

  php-fpm:
    volumes:
      - .:/laravel:consistent

  postgres:
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/conf/:/docker-entrypoint-initdb.d/
      - ./docker/postgres/data/:/var/lib/postgresql/data/

  redis:
    volumes:
      - ./docker/redis/data/:/data
    ports:
      - 6379:6379

  redis-webui:
    ports:
      - ${REDIS_WEBUI_PORT}:80

  maildev:
    ports:
      - ${MAILDEV_HTTP_PORT}:80
      - ${MAILDEV_SMTP_PORT}:25
