name: CI
on:
  push:
    branches:
#      - master
      - 'php-**'
    paths:
      - 'docker/php-fpm/Dockerfile'
jobs:
  test:
    name: Push to GitHub Packages stryber-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branc

      # replace master to latest in branch name
      # save branch name to env.action_state
      - name: Get branch name
        run: branch=${{ steps.extract_branc.outputs.branch }}
          && echo "branch=${branch//master/latest}" >> $GITHUB_ENV

      - name: Test variable
        run: echo "stryberventures/stryberphpdockerimages/stryber-${{ env.branch }}"

#      - name: Build and push PHP Docker images
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          dockerfile: docker/php-fpm/Dockerfile
#          registry: docker.pkg.github.com
#          repository: stryberventures/stryberphpdockerimages/stryber-${{ env.branch }}
#          target: php-base
#          tag_with_ref: true
