name: CI
on: [pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/php-fpm/Dockerfile
          registry: docker.pkg.github.com
          repository: stryberventures/stryberphpdockerimages/stryber-php
          target: php-base
          tags: ${{ github.sha }}, org.opencontainers.image.revision
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
