name: CI
on:
  push:
    branches:
#      - master
      - 'php-**'
    paths:
      - 'docker/php-fpm/Dockerfile'
jobs:
  test:
    name: Push to GitHub Packages stryber-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branc

#      # extract branch name
#      - name: Extract branch name
#        if: github.event_name != 'pull_request'
#        shell: bash
#        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $BRANCH_NAME
#        id: extract_branch
#
#      # extract branch name on pull request
#      - name: Print branch name
#        if: github.event_name == 'pull_request'
#        shell: bash
#        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $BRANCH_NAME

      # print branch name
      - name: Get branch name
        run: branch=${{ steps.extract_branc.outputs.branch }}
          && echo "action_state=${branch//master/latest}" >> $GITHUB_ENV

      - name: Test variable
        run: echo ${{ env.action_state }}

#      - name: Build and push PHP Docker images
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          dockerfile: docker/php-fpm/Dockerfile
#          registry: docker.pkg.github.com
#          repository: stryberventures/stryberphpdockerimages/stryber-${{ env.action_state }}
#          target: php-base
#          tag_with_ref: false
