name: CI
on: [pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/php-fpm/Dockerfile
          registry: docker.pkg.github.com
          labels: ${{ github.sha }}, org.opencontainers.image.revision
          repository: stryberventures/stryberphpdockerimages/stryber-php
          tags: latest
          target: php-base
