name: CI
on:
  push:
    branches:
      - 'php-**'
    paths:
      - 'Dockerfile'
jobs:
  build-base:
    name: Push to GitHub Packages stryber-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branc

      - name: Save branch name to env variable
        run: branch=${{ steps.extract_branc.outputs.branch }}
          && echo "BRANCH=${branch//master/latest}" >> $GITHUB_ENV

      - name: Add repository variable
        run: echo "INPUT_REPOSITORY=stryberventures/stryberphpdockerimages/stryber-${{ env.BRANCH }}" >> $GITHUB_ENV

      - name: Build and push PHP base Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
          repository: "${{ env.INPUT_REPOSITORY }}"
          target: base
          tag_with_ref: false
          tags: latest

      - name: Build and push PHP dev Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
          repository: "${{ env.INPUT_REPOSITORY }}-dev"
          target: dev
          tag_with_ref: false
          tags: dev
