name: CI
on:
  push:
    branches:
      - master
      - 'php-**'
jobs:
  test:
    name: Push to GitHub Packages stryber-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/php-fpm/Dockerfile
          registry: docker.pkg.github.com
          repository: stryberventures/stryberphpdockerimages/stryber-php
          target: php-base
          tag_with_ref: true
